---
splunk:
  conf:
    inputs:
      content:
        prometheus://prom-server-1:
          URI: "http://prometheus:9090/federate"
          match: '{__name__=~"..*"}'
          index: prometheus
          sourcetype: prometheus:metric
          host: prometheus
          interval: 30
          disabled: 0